asyncapi: '2.0.0'
info:
  title: Telemetry Consumer Async API
  version: '1.0.0'

servers:
  test:
    url: api.test.telemetry.ru
    protocol: kafka

channels:
  device_updates:
    description: Channel for receiving device updates
    subscribe:
      summary: Subscribe to device updates
      operationId: subscribeDeviceUpdates
      message:
        contentType: application/json
        payload:
          type: object
          properties:
            operationType:
              type: string
              description: The type of operation performed on the device.
              enum:
                - create
                - update
                - delete
            data:
              $ref: '../common/models.yaml#/components/schemas/Device'