asyncapi: '2.0.0'
info:
  title: Device Control Async API
  version: '1.0.0'
servers:
  test:
    url: api.test.device-control.ru
    protocol: kafka
channels:
  device_updates:
    description: Channel for publishing device updates
    publish:
      summary: Publish device data
      operationId: publishDeviceData
      message:
        contentType: application/json
        payload:
          type: object
          properties:
            operationType:
              type: string
              enum:
                - create
                - update
                - delete
            data:
              $ref: '../common/models.yaml#/components/schemas/Device'